# Generated by Django 5.2.15 on 2026-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='agenda/')),
            ],
        ),
    ]
