# Generated by Django 5.2.15 on 2026-06-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(default=None, upload_to='berita/'),
            preserve_default=False,
        ),
    ]
