# Generated by Django 5.2.15 on 2026-06-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_berita_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='berita/'),
        ),
    ]
