# Generated by Django 5.2.15 on 2026-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
