# Generated by Django 5.2.15 on 2026-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
