# Generated by Django 5.2.15 on 2026-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0002_divisi_pengurus_deskripsi_pengurus_divisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='is_koordinator',
            field=models.BooleanField(default=False),
        ),
    ]
